# Generated by Django 3.1 on 2020-08-28 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='링크')),
                ('tag', models.CharField(max_length=200, null=True, verbose_name='태그')),
                ('comments', models.CharField(max_length=200, null=True, verbose_name='코멘트')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.URLField(null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
            ],
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성시간')),
            ],
        ),
    ]
