# Generated by Django 3.1 on 2020-08-15 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200812_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Favorite',
        ),
    ]
