# Generated by Django 3.1 on 2020-08-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='author',
        ),
        migrations.AlterField(
            model_name='add',
            name='tag',
            field=models.TextField(null=True, verbose_name='태그'),
        ),
    ]
