# Generated by Django 3.1 on 2020-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200823_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='title',
        ),
        migrations.AddField(
            model_name='add',
            name='comments',
            field=models.CharField(max_length=200, null=True, verbose_name='코멘트'),
        ),
    ]
